(cl:in-package #:common-lisp-user)

(defpackage #:concrete-syntax-tree
  (:nicknames #:cst)
  (:use #:common-lisp)
  (:shadow #:first
           #:second
           #:third
           #:fourth
           #:fifth
           #:sixth
           #:seventh
           #:eighth
           #:ninth
           #:tenth
           #:nth
           #:rest
           #:atom
           #:consp
           #:cons
           #:list
           #:null
           #:keyword)
  (:export #:cst
           #:parent
           #:source
           #:first
           #:second
           #:third
           #:fourth
           #:fifth
           #:sixth
           #:seventh
           #:eighth
           #:ninth
           #:tenth
           #:nthrest
           #:nth
           #:rest
           #:atom
           #:consp
           #:cons
           #:list
           #:null
           #:raw
           #:listify
           #:separate-ordinary-body
           #:separate-function-body
           #:list-structure
           #:proper-list-p
           #:cst-from-expression
           #:canonicalize-declaration-specifier
           #:reconstruct
           #:parser
           #:parse
           #:ordinary-lambda-list
           #:parse-ordinary-lambda-list
           #:parse-generic-function-lambda-list
           #:parse-specialized-lambda-list
           #:parse-defsetf-lambda-list
           #:parse-define-modify-macro-lambda-list
           #:parse-define-method-combination-lambda-list
           #:parse-destructuring-lambda-list
           #:parse-macro-lambda-list
           #:target
           #:*ordinary-required-parameter-group*
           #:*ordinary-optional-parameter-group*
           #:*ordinary-rest-parameter-group*
           #:*ordinary-key-parameter-group*
           #:*aux-parameter-group*
           #:*ordinary-lambda-list*
           #:*generic-function-optional-parameter-group*
           #:*generic-function-key-parameter-group*
           #:*generic-function-lambda-list*
           #:*specialized-required-parameter-group*
           #:*specialized-lambda-list*
           #:*environment-parameter-group*
           #:*defsetf-lambda-list*
           #:*define-modify-macro-lambda-list*
           #:*whole-parameter-group*
           #:*define-method-combination-lambda-list*
           #:*destructuring-required-parameter-group*
           #:*destructuring-rest-parameter-group*
           #:*destructuring-lambda-list*
           #:*macro-lambda-list*
           #:*standard-grammar*
           #:*ordinary-lambda-list-grammar*
           #:*generic-function-lambda-list-grammar*
           #:*specialized-lambda-list-grammar*
           #:*defsetf-lambda-list-grammar*
           #:*define-modify-macro-lambda-list-grammar*
           #:*define-method-combination-lambda-list-grammar*
           #:*destructuring-lambda-list-grammar*
           #:*macro-lambda-list-grammar*))
